ReactTestInstance = {
    _fiber: <ref *1> FiberNode {
      tag: 1,
      key: null,
      elementType: [Function: Component] {
        displayName: 'TextInput',
        '$$typeof': Symbol(react.forward_ref),
        render: [Function: TextInput],
        propTypes: [Object],
        State: [Object]
      },
      type: [Function: Component] {
        displayName: 'TextInput',
        '$$typeof': Symbol(react.forward_ref),
        render: [Function: TextInput],
        propTypes: [Object],
        State: [Object]
      },
      stateNode: Component {
        props: [Object],
        context: {},
        refs: {},
        updater: [Object],
        _reactInternals: [Circular *1],
        _reactInternalInstance: {},
        state: null
      },
      return: FiberNode {
        tag: 5,
        key: null,
        elementType: 'View',
        type: 'View',
        stateNode: [Object],
        return: [FiberNode],
        child: [Circular *1],
        sibling: null,
        index: 0,
        ref: null,
        pendingProps: [Object],
        memoizedProps: [Object],
        updateQueue: null,
        memoizedState: null,
        dependencies: null,
        mode: 0,
        flags: 0,
        nextEffect: null,
        firstEffect: null,
        lastEffect: null,
        lanes: 0,
        childLanes: 0,
        alternate: null,
        actualDuration: 0,
        actualStartTime: -1,
        selfBaseDuration: 0,
        treeBaseDuration: 0,
        _debugID: 78,
        _debugSource: null,
        _debugOwner: [FiberNode],
        _debugNeedsRemount: false,
        _debugHookTypes: null
      },
      child: FiberNode {
        tag: 5,
        key: null,
        elementType: 'TextInput',
        type: 'TextInput',
        stateNode: [Object],
        return: [Circular *1],
        child: null,
        sibling: null,
        index: 0,
        ref: null,
        pendingProps: [Object],
        memoizedProps: [Object],
        updateQueue: null,
        memoizedState: null,
        dependencies: null,
        mode: 0,
        flags: 0,
        nextEffect: null,
        firstEffect: null,
        lastEffect: null,
        lanes: 0,
        childLanes: 0,
        alternate: null,
        actualDuration: 0,
        actualStartTime: -1,
        selfBaseDuration: 0,
        treeBaseDuration: 0,
        _debugID: 80,
        _debugSource: null,
        _debugOwner: [Circular *1],
        _debugNeedsRemount: false,
        _debugHookTypes: null
      },
      sibling: null,
      index: 0,
      ref: null,
      pendingProps: {
        style: [Object],
        placeholder: 'Password',
        placeholderTextColor: '#003f5c',
        secureTextEntry: true,
        onChangeText: [Function: onChangeText]
      },
      memoizedProps: {
        style: [Object],
        placeholder: 'Password',
        placeholderTextColor: '#003f5c',
        secureTextEntry: true,
        onChangeText: [Function: onChangeText]
      },
      updateQueue: {
        baseState: null,
        firstBaseUpdate: null,
        lastBaseUpdate: null,
        shared: [Object],
        effects: null
      },
      memoizedState: null,
      dependencies: null,
      mode: 0,
      flags: 1,
      nextEffect: null,
      firstEffect: null,
      lastEffect: null,
      lanes: 0,
      childLanes: 0,
      alternate: null,
      actualDuration: 0,
      actualStartTime: -1,
      selfBaseDuration: 0,
      treeBaseDuration: 0,
      _debugID: 79,
      _debugSource: undefined,
      _debugOwner: FiberNode {
        tag: 0,
        key: null,
        elementType: [Function: Login],
        type: [Function: Login],
        stateNode: null,
        return: [FiberNode],
        child: [FiberNode],
        sibling: null,
        index: 0,
        ref: null,
        pendingProps: [Object],
        memoizedProps: [Object],
        updateQueue: null,
        memoizedState: [Object],
        dependencies: null,
        mode: 0,
        flags: 1,
        nextEffect: null,
        firstEffect: [FiberNode],
        lastEffect: [FiberNode],
        lanes: 0,
        childLanes: 0,
        alternate: null,
        actualDuration: 0,
        actualStartTime: -1,
        selfBaseDuration: 0,
        treeBaseDuration: 0,
        _debugID: 60,
        _debugSource: null,
        _debugOwner: [FiberNode],
        _debugNeedsRemount: false,
        _debugHookTypes: [Array]
      },
      _debugNeedsRemount: false,
      _debugHookTypes: null
    }
}